### ISSUE TITLE
Bugs report (Spoiler)

### ISSUE THREAD

**Issue by Xorboth** [07th-mod/umineko-question#112]
I discovered a few bugs when playing Umineko with the patch applied, so I'm gonna report them here.
There may be spoilers if you haven't finished the question arcs yet.

A few infos about my system:
I installed the Steam version of Umineko, and then I applied the patch.
Question arc installed on 09/09/2018.
Patch for question arc installed on 11/09/2018.

Bugs:
1) Missing Voice
Episode 1
Maria is supposed to start to sing, but there's no voice at all
This is when she's supposed to sing: https://youtu.be/RSSH7CfOcuM?t=17711

**Should be fixed now in https://github.com/07th-mod/umineko-question/commit/5e64db4d291b9f541f4718800deffcf0603cb5cf**

2) Bugged characters menu
Episode 1
I'm unable to see characters on the menu
Screenshots when this happens:
![c03](https://user-images.githubusercontent.com/45687969/49645678-249c0380-fa1d-11e8-9d61-59075cf1f015.png)
![c04](https://user-images.githubusercontent.com/45687969/49645690-2b2a7b00-fa1d-11e8-9d8c-2ac71dcf1417.png)

**Confirmed, and I know what causes it, but not fixed yet. See https://github.com/07th-mod/umineko-question/issues/87**

3) Missing CG (Not Sure)
Episode 3
I'm not sure about this, but in a gameplay I discovered that the giant's shield should be supposed to glow
How it is supposed to be: https://youtu.be/YpWljmWnHDc?t=25786
Hot it is with the patch:
![c05](https://user-images.githubusercontent.com/45687969/49645704-354c7980-fa1d-11e8-89a9-9ee338e7e11d.png)

**Comment by drojf** [comment]
I looked into "3. Missing CG (Not Sure)" just now. It appears that that image is actually a screenshot taken from one of the movies in the ps3 game `movie\no02.pam`. 

I don't really want to fix just that instance, since there are various other effects which are probably missing as well, but fixing it properly would take quite some effort too (either by emulating the effects by making lots of screencaps of the video, or legitimately inserting the video).

So for now I will just leave it as-is. I'll create a new issue "Movies not inserted" instead: https://github.com/07th-mod/umineko-question/issues/139
