### ISSUE TITLE
Layered voice volume

### ISSUE THREAD

**Issue by ChrisE87** [07th-mod/umineko-question#13]
It seems like whenever multiple voice samples are played at the same time, one of them has at least twice the volume than the rest, making it very very loud in comparison to the rest of the novel.

**Comment by marakeusz** [comment]
I have similiar issue.

I wrote https://github.com/07th-mod/umineko-question/issues/11#issuecomment-249424065 about possible reason for that.

**Comment by drojf** [comment]
here is my old comment on this issue for reference: https://gist.github.com/drojf/a28f8bf8834f0088ac23b9691bfaa190

I guess this bug is part of a larger bug where changing the default_vol setting screws everything up as the script doesn't deal with it properly. 

As long as there's no audio clipping issues, we can revert back to using default volumes for everything. I first brought up the audio clipping issue here: https://github.com/07th-mod/umineko-question/issues/1#issuecomment-238067587 . The main reason I was so concerned about it was because when I played the old UmiTweak version I had the same audio clipping issue.

There is also the 'alternate voice player' option as described: https://github.com/07th-mod/umineko-question/issues/11#issuecomment-249428954

**Comment by drojf** [comment]
This bug shouldn't happen anymore since we reset the volumes close to the default:

```
numalias default_vol, 70
voicevol 75
```
