### ISSUE TITLE
(linux) kuina.ogg bugged

### ISSUE THREAD

**Issue by ZahnPastor** [07th-mod/umineko-question#132]
[link to kuina.ogg from original game removed]

i uploaded my defect kuina.ogg to google drive, and its showing the error there too, as i was told to make a new issue from #111 

for some reason, it doesnt black out again for a while, but there is still a skip at around the 0:53 second mark, if you try to follow the beat of the song, youll notice the skip there

i had this issue with a bugged kuina.ogg on my previous PC as well, so i think probably more people are affected by this

**Comment by drojf** [comment]
The file must be corrupted somehow - by sheer coincidence I tried playing it in my browser and it does the 'black out' for a little bit thing.

Then I tried importing it into audacity, and in that case it does the 'skip a beat' thing (I originally tested it in foobar and it also does the 'skip a beat' thing, which is probably why I didn't notice it).

So I can absolutely confirm the bug - I'll definitely put a 'good' version into the patch as it's fairly easy to do. Thanks for reporting the bug. 

Also since the mod doesn't actually modify the BGM, I guess it's a bug with the unmodded game too (maybe even in the Japanese game!). It might be difficult for MangaGamer to fix it themselves if it were a problem with the original Japanese game files (because they would need to obtain the audio themselves). If they made the mistake or corrupted the files themselves somehow, then they might be able to fix it.

Here is the fixed version which I'll use, from the DVAC-0001 album (ogg rencoded from FLAC): https://1drv.ms/u/s!Ar-lAVeetlqh3ir1YIdV635DsVBO If you still hear any problems with it please let me know.

If you don't mind I'll remove both our music links from github after a couple weeks (both files will still be available elsewhere anyway), just to be safe.

**Comment by ZahnPastor** [comment]
yeah, the issue is not there in the version you uploaded
