### ISSUE TITLE
No ADV

### ISSUE THREAD

**Issue by azeem400** [07th-mod/umineko-question#146]
- Even though I toggle ADV mode, it doesn't appear.
- ![image](https://user-images.githubusercontent.com/56945198/67446565-a6b1fe00-f5d6-11e9-8eb1-dbed1c81336f.png)
- My operating system is Windows 10
- I installed the game 10 Months ago.
- I am running the Full Patch.
- I installed the game using the Automatic Installer.
- My computer is a gaming pc

**Comment by azeem400** [comment]
Oh, here is the result with above settings.
![image](https://user-images.githubusercontent.com/56945198/67446667-f7c1f200-f5d6-11e9-84df-1e16bf4ac39a.png)

**Comment by drojf** [comment]
Can you start a new game, then try toggling the settings? 

Also, you might be in a part of the game where you're not allowed to toggle ADV mode or something similar.

We've had a fair number of fixes to the patch since 10 months ago. It may be worth updating once you complete the current episode (not sure if it will fix this issue, though)

**Comment by drojf** [comment]
Closing this as no responsea fter 2 years
