### ISSUE TITLE
Voice is played before previous one is finished

### ISSUE THREAD

**Issue by marakeusz** [07th-mod/umineko-question#22]
During the game I came across few (or a lot) situations when the dialogues were progressing a lot faster than they should. Meaning - one voice file was not completely played and the second one has to start. The reason was - some lines are ended with **/** (ignore line feed) sign and there is no wait sign in script (**@** or **\**) before next line's **dwave**.
### Example:

> langjp「だ、駄目だよ、戦人くんはまだ未成年じゃないか！@　未成年の飲酒は発育に悪影響を及ぼす可能性が…、/
> langjp^^!d1000って、う〜ん。」@
> langen:dwave 0, geo_1e10:^"Th-That's no good, Battler-kun! You're still a minor!^@:dwave 0, geo_1e11:^  Don't you know alcohol can stunt the growth of...^**/**
> langen:delay 2000:**dwave** 0, geo_1e12:^...um, never mind."^@

In this case **delay 2000** was not enough and first voice file had to be stopped in order to play the second one _(um, never mind)_. The issue is tricky - I do not think it is possible (without a lot of effort) to prepare delays which would match every voice file's length.

So I figured that maybe adding the **@** (wait) sign would be improvement.

I made the script which is looking for lines like that (with **/** in the end) and checks if the next lines are having wait signs. If not - **@** is inserted before dwave. If anyone interested python script is here  https://github.com/marakeusz/umineko-question/blob/additional_pauses_test/provideWaitsToScript.py and updated utf files is on [my branch](https://github.com/marakeusz/umineko-question/commit/bbb546f97c331aa80b96742a079d0682e5983fc5).

Above line is now looking like this (**@** before :dwave):

> langen:delay 2000**@:dwave** 0, geo_1e12:^...um, never mind."^@

**Comment by drojf** [comment]
> I do not think it is possible (without a lot of effort) to prepare delays which would match every voice file's length.

You could do this by extracting the length of all the sound files and then setting the delay appropriately...doesn't sound that bad to me :D . But yea your solution sounds fine for now. Unfortunately I can't check the changes on your repository (it says 313,663 lines changed).
Just wondering, approximately how many lines were changed with your python script?

I remember we discussed a long time ago in that huge patch thread about the `delay` commands, and someone said "it only affects if you're in auto mode" but from your description it's also used for timing / dramatic reasons, probably even in the original script with no voices. I wonder if the umitweak people manually adjusted all the delays in their script.

Thanks for reporting (and fixing!) all these bugs btw. 

edit: well I already had ffmpeg/ffprobe installed to extract the audio file length, so I thought I'd quickly have a go at it. Unfortunately my script runs slowly, and it's getting a bit late so I haven't run the script on the entirety of the files. I just did this for fun, you don't have to actually incorporate this into the script changes. If you do use it, remember to never decrease the delay lengths, only increase them, in case the text takes longer to read than the voice takes to play.

python code: https://gist.github.com/drojf/7ee63088b1d0751f64ae8d557d60e77c

**Comment by marakeusz** [comment]
1969 lines were changed but apparently git's diff tool is interpreting it as all the lines were removed and new were added... (that's certainly not the case). I will look into it.

> from your description it's also used for timing / dramatic reasons, probably even in the original script with no voices.

Exactly. E.g. there are several lines where we have got "@:delay xxx:" which I am planning to change to ":delay XX@:" because it IS really annoying when after click there is 1-3 seconds pause.

Cool script to extract audio length. I will do something with that. Thanks

**Comment by marakeusz** [comment]
https://github.com/marakeusz/umineko-question/commit/bbb546f97c331aa80b96742a079d0682e5983fc5 apparently 1940 additions is also to much for github to handle...

**Comment by DoctorDiablo** [comment]
Most of the delays are done to add an intentional dramatic pause.  I'm not sure if we should change that unless there's no other way to fix these issues.

The Steam version runs on a different engine than the old umitweak version, and the delay command behaves a little differently there.  I took the delays from the umitweak script and doubled them, which usually worked... but that wasn't an exact science, the old delays were not necessarily accurate, and my code didn't always handle oddly formatted lines.

Also, one problem I ran into while adding the voice clips that I want to make sure we avoid... if the delay line is in the wrong position it causes a delay to happen before the text and audio are played.  So the player clicks, nothing happens for 2 seconds, and then the text/audio come in.  The delay is supposed to happen after the text, or else it feels like the game is just lagging.

**Comment by marakeusz** [comment]
@DoctorDiablo, I agree. I will not do any further changes in order to fix issue I spoke of in first post. Massive changes in delays would be too hard to test. My "solution" which are additional pauses should be fine (probably safer).

> So the player clicks, nothing happens for 2 seconds, and then the text/audio come in. The delay is supposed to happen after the text, or else it feels like the game is just lagging.

Hm. By using regex we can replace:
@(:delay [0-9]+) with
\1@
And 26 cases of that problem will disappear.

Probably there are more problems with delays but it is hard to say without playing whole game. I am during 2nd episode so I will report.

**Comment by drojf** [comment]
Not breaking things sounds like a good idea :)

Here is the output of the program so you don't need to run it yourself, maybe it can be used for something later: https://gist.githubusercontent.com/drojf/f781a54fe8b96fa74bd09fe9386bdded/raw/791f8cd422192c5d67fa7dda0e13e7ef046bfb89/audio_lengths.txt

**Comment by DoctorDiablo** [comment]
That's actually really useful.  But programmatically updating all of the delays with those values might be difficult because the length of the delay corresponds to the length of _previous_ the voice clip, which may be one or more lines up.  For example:

> langen:dwave 0, geo_1e23:^  Up you go-^/
> langen:delay 1400:dwave 0, geo_1e24:^nnngg...^/
> langen:delay 1600:dwave 0, geo_1e25:^I guess you've gotten a bit too heavy to play airplane with..."^\

If you can parse the previous voice tag out (geo_1e23 and geo_1e24 in this example), it should be easy to look up the corresponding file name from the stralias section in the script, then map that to your audio_lengths.txt.  Based on your mapping, it would end up being:

> langen:dwave 0, geo_1e23:^  Up you go-^/
> langen:delay 699:dwave 0, geo_1e24:^nnngg...^/
> langen:delay 1896:dwave 0, geo_1e25:^I guess you've gotten a bit too heavy to play airplane with..."^\

Another complication is that not all delays have voice clips, so we don't want to accidentally insert bogus delay length in them:

> langen^You've probably guessed by now, but to put it simply...^/
> langjp^^!d900……まぁその、右代宮家は大富豪なわけさ。@
> langen:delay 1800^...well, the Ushiromiya family is just rolling in dough.^@

**Comment by drojf** [comment]
ah, I still agree that we should not adjust the delays for now unless we find an easy way to do it/we have nothing else to fix. I just posted the lengths in case we choose to use it later, however unlikely that might be, so I don't need to dig out the script and run it again.

----

To eliminate the 'bogus delay length insertion', you'd only want to change the delay if the previous dwave line did not have an `@` or `\` symbol (click wait or end of page wait), which is exactly the problem cases marakeusz has brought up in this issue. The previous line must also at the very least contain a dwave command in it - if the previous line was a pure text line then you wouldn't want to change it. That should be enough to reduce the number down small enough. You could then output those lines only and test them just by clicking through them (although I wonder how many there are  - there are 2364 total delay lines in the script)

1. identify delay on the third line
2. look at the most previous english line (or maybe many lines up? not sure)
3. check if it contains a dwave command - if it doesn't, then exit
3. check if the line ends with an `@` or `\` - if it does, then exit
4. change the delay value

Examples:
```
langen^You've probably guessed by now, but to put it simply...^/
langjp^^!d900……まぁその、右代宮家は大富豪なわけさ。@
langen:delay 1800^...well, the Ushiromiya family is just rolling in dough.^@
```
This would fail because there is no `dwave` on the immediately previous english line
```
langen:dwave 0, kum_1e29:^".........Rumor has it...^/
langjp^^!d900…六軒島はその昔、」@
langen:delay 1800:dwave 0, kum_1e30:^...that long ago, Rokkenjima was-"^@
```

This would pass because there is a dwave not followed by `@` or`\`:
```
langen:dwave 0, mar_1e16:^"......Like George onii-chan?^@/
langjp^^!s0　…/
langjp^^!d200/
langjp…/
langen^^!s0^  ...^/
langen:delay 400^...^/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langen:delay 400^...^/
langen:delay 400^...^/
```
This would not match, either because the previous line does not contain `dwave`, or if you look back multiple lines, because the next closest dwave line ended with a `@`

This whole process is more or less is equivalent to stringsplitting on `@` and `\` (not contained within `^` quotes), and then only match `delay` commands to `dwave` commands within those islands of text between `@` and `\`.

It does seem a bit finicky though, and I'm sure I would miss some cases doing it this way.

----
I also just realized that the japanese script uses the [`!d` shortcut](http://unclemion.com/onscripter/api/NScrAPIm.xml#_bang-d) to do delays

```
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langjp^^!d200…/
langen:delay 400^...^/
langen:delay 400^...^/
langen:delay 400^...^/
langen:delay 400^...^/
```

**Comment by drojf** [comment]
This should be fixed as of here: https://github.com/07th-mod/umineko-question/issues/92
