### ISSUE TITLE
Voice alias never used

### ISSUE THREAD

**Issue by marakeusz** [07th-mod/umineko-question#25]
I came across the line in which George is speaking but there was no voice. The reason is clear when we get a look in the script

```
langjp「……いいよ、そんな弁え。@/
langen:dwave 0, geo_2e249:^"...Don't worry about `understanding your place' in that sense.^@/

ld r,$GEO_HohoemiA1,80

langjp仕事中はともかく、こうして休み時間に過ごす時の僕らは、あの頃から変わらない、仲良しで居続けたいね。」\
;＜譲治
langen^  When you're on the job is one thing, but when you're taking your break and with us, like now, ^@^I'd rather you stay and be friendly, just like the old days."^\
```

The 2nd line is not having **dwave.** I figured it would be a good place for file which would be called **geo_2e250** (since previous one was ...49). And in fact that seems to be the case. geo_2e250 is listed along with other aliases but it is never used.

Maybe someone familiar with how the dwaves were put in the script - can figure why that line was skipped and process may be improved? I have a feeling that that line is not first/last occurrence of such problem.

**Comment by drojf** [comment]
@DoctorDiablo  wrote the java program that inserted of voices. I don't think we ever ran a script to check whether all the voice files were used though, so we wouldn't know if that was the case. For example, check in the old umitweak which voices were used, check in our script which voices were used, then diff them and see what's missing.

Indeed, in the original umitweak script the dwave is there:
```

ld r,$GEO_HohoemiA1,80

;仕事中はともかく、こうして休み時間に過ごす時の僕らは、あの頃から変わらない、仲良しで居続けたいね。」\
;＜譲治
dwave 0, geo_2e250`Forget when you're working, when you're taking your break, like now, I want you to stay with us and be friendly."`\ 
E_N 
delay 200
```

marakeusz you can view the orignal umitweak script here, it might be helpful when you are troubleshooting script issues: https://github.com/07th-mod/umineko-question/blob/master/dev/umineko_fullvoice.txt

**Comment by ChrisE87** [comment]
> I have a feeling that that line is not first/last occurrence of such problem.

Definitely not. From my observation, it is mostly the case when some person has a larger speech in a single screen that is separated by user clicks. Usually some line in the middle is left out in that case.

**Comment by DoctorDiablo** [comment]
The code that inserted the voices could only successfully place 95% of the voice tags because of formatting anomalies (roughly 38k out of 40k lines), so I made it run a check against the script after the voices were inserted to see if any voice tags were used twice, or are missing.  [This](https://github.com/07th-mod/umineko-question/blob/master/InDevelopment/UminekoVoiceParser/Output/writing_errors.utf) was the output.  I mad to manually correct all of these.  Also, after all that was complete I searched in the script for `langen^"` because voiced lines are supposed to start with a quote, and I manually fixed any of those that were missing a voice tag after all that.

The voice tag you mentioned is interestingly not listed in the error log and does not start with a quote either.  So I did a quick search for `langen^ ` with a space at the end.  It found 58 matches, and some of them look like they need voice tags.  That's probably a good way to eliminate the rest of these.

**Comment by marakeusz** [comment]
Cool, I did not see umitweak script yet.

@DoctorDiablo, thanks for explanation.

I made the script to isolate the aliases which are not used in any dwave. At first it was 618 aliases but then I checked umitweak script as well (which was kind of hard - your 0.utf's dwaves are much cleaner) and number of unused aliases was similar. So the list is narrowed to 115. [List here.](http://pastebin.com/c7kgUF4s).

**Comment by DoctorDiablo** [comment]
Awesome, I'll go through your list later today and fix any other missing voice lines.

**Comment by DoctorDiablo** [comment]
I fixed all of the more straightforward lines that you identified, but some of the lines turned out to have no equivalent in the new script because the script was re-translated and edited for the steam version.  I didn't want to change any of the actual text, so I had to use my better judgement about when to insert voice lines or not.  For example:

old
> bea:dwave 0, bea_9e281`"Well then.`@dwave 0, bea_9e282`  ...Did you enjoy it?`@dwave 0, bea_9e283` The game just now."`\ 

new
> langen:dwave 0, bea_9e281:^"Well then,^@:dwave 0, bea_9e282:^ ...did you find that game enjoyable?"^@

**Comment by marakeusz** [comment]
Awesome :) So [44 aliases](http://pastebin.com/N6BjraYB) left. I wen through that list and umitweak script and I understand what you mean. Some voices are just not matching the updated translation. Thanks for fixes.

**Comment by drojf** [comment]
I'll mark this as closed. Thanks @marakeusz
