### ISSUE TITLE
background seems to shift a bit to the left

### ISSUE THREAD

**Issue by HyperMR** [07th-mod/umineko-question#30]
background seems to shift a bit to the left in the meta world 
(episode 2 spoilers)
![umineko1to4_2016-10-06_21-24-33](https://cloud.githubusercontent.com/assets/22666897/19166075/de7d9d1a-8c0e-11e6-90c8-cbae9aec0a76.jpg)

**Comment by drojf** [comment]
Looks like hana_d.png and hana_u.png which are used by the function `mset` and `meta_set` weren't resized by me. Here are the edited images. I also resized 'cinema.bmp' since it looks like it should be resized as well.

[issue_30_images.zip](https://github.com/07th-mod/umineko-question/files/517487/issue_30_images.zip)

If anyone wants to fix this kind of issue in the future, it's pretty easy. Just determine which image it is by either browsing through the images or looking it up in the script. Then:

If it's a 1280x[height] image, resize it to 1707x[height] image (either photoshop/redraw it nicely if required, or just resize it). These images are usually .png.

If it's a 640x[height] image, resize it to 854x[height]. These images are usually .bmp.

**Comment by drojf** [comment]
Looks like `hana_d.png` and `hana_u.png` which are used by the function `mset` and `meta_set` weren't resized by me. Here are the edited images. I also resized 'cinema.bmp' since it looks like it should be resized as well.

The images should be placed in `Umineko\bmp\efe`: [issue_30_images.zip](https://github.com/07th-mod/umineko-question/files/517496/issue_30.zip)

If anyone wants to fix this kind of issue in the future, it's pretty easy. Just determine which image it is by either browsing through the images or looking it up in the script. Then:

If it's a 1280x[height] image, resize it to 1707x[height] image (either photoshop/redraw it nicely if required, or just resize it). These images are usually .png.

If it's a 640x[height] image, resize it to 854x[height]. These images are usually .bmp.

**Comment by Knurek-NC** [comment]
This fixes the background issue, but the character sprites are still shifted to the left (as in the above picture).

**Comment by Knurek-NC** [comment]
There are also problems with function that blanks the screen, as can be seen in the below screenshot:

![20161009080219_1](https://cloud.githubusercontent.com/assets/22718168/19218387/dc71daf4-8df8-11e6-9a71-11918ebbf298.jpg)
](url)

**Comment by drojf** [comment]
na it's ok, this is a related issue, so it's good to put it in here. If there is some sort of special effect or sprite/background which only partially covers the screen, it's probably just that it hasn't been resized (well, except for the issue you showed me today with the offset sprites) 

```
	Line 112465: lsp bgsp,":c;bmp\background\efe\black.bmp",0,0
	Line 112494: lsp bgsp,":c;bmp\background\efe\black.bmp",0,0
	Line 112898: lsp bgsp,":c;bmp\background\efe\black.bmp",0,0
	Line 112959: lsp bgsp,":c;bmp\background\efe\black.bmp",0,0
	Line 237291: lsp 899,":c;bmp\background\efe\black.bmp",0,0,50
```

The current `black.png` needs to be deleted and replaced with the following `black.bmp` in `umineko\bmp\background\efe\black.bmp` (854x480 resolution). A zip file containing all images for this issue is attached.

[issue30.zip](https://github.com/07th-mod/umineko-question/files/518175/issue30.zip)

**Comment by drojf** [comment]
Just checked and this is definitely fixed in the latest release.
