### ISSUE TITLE
Small (original) backgrounds in EP 2

### ISSUE THREAD

**Issue by Maelstrom1** [07th-mod/umineko-question#32]
About the time Kanon takes Beatrice lunch on day 1, a random background occasionally when no sprites are up for a single page of dialogue. Here are the 3/4 times it happened:
<img width="960" alt="small background" src="https://cloud.githubusercontent.com/assets/20371049/19216525/b0a979ce-8d8d-11e6-9255-3623b88670b8.png">
![small background 2](https://cloud.githubusercontent.com/assets/20371049/19216527/b5d2a15a-8d8d-11e6-9482-36d0442c4dde.jpg)
![small background 3](https://cloud.githubusercontent.com/assets/20371049/19216526/b5d159b2-8d8d-11e6-8fc5-584c11c942d1.jpg)

**Comment by drojf** [comment]
Yea, this is a bug in the script. The following images are affected:

```
stralias rose_2a,":b;bmp\background\garden\rose_2a.png"  ;魔女空間薔薇庭園　１枚目
stralias rose_2b,":b;bmp\background\garden\rose_2b.png"  ;魔女空間薔薇庭園　２枚目
stralias rose_2c,":b;bmp\background\garden\rose_2c.png"  ;魔女空間薔薇庭園　３枚目
stralias rose_3a,":b;bmp\background\garden\rose_3a.png"  ;魔女空間薔薇庭園　１枚目
stralias rose_3b,":b;bmp\background\garden\rose_3b.png"  ;魔女空間薔薇庭園　２枚目
stralias rose_3c,":b;bmp\background\garden\rose_3c.png"  ;魔女空間薔薇庭園　３枚目
stralias Mvip_1e,":b;bmp\background\mainbuilding\mvip_1e.png"  ;本館　貴賓室　天井　５枚目　
```

They should all have the ":b" removed if we are to use the original game images still. 

Just wondering before I try to fix anything - these images are the original images because there is no corresponding PS3 image. Would you guys prefer to use the most similar PS3 image, or use the original game's image? In this case, it would be a picture of some lights, but not the same ones as in this picture. The other cases are of the garden, so it'd be some PS3 image of the garden.

garden images: http://imgur.com/a/lXGy8

I think I made the decision a while back to use the original images, but it's quite distracting that the art style changes randomly...

**Comment by DoctorDiablo** [comment]
I'd suggest using the most similar PS3 image.  That's what you'd see if you were actually playing the PS3 version, and that's how we've been doing things in the Higurashi mods.

**Comment by drojf** [comment]
Here is the fixed image. It turns out all the rose_ images I talked about above are not used in the script.

[mvip_1e.png for issue 32.zip](https://github.com/07th-mod/umineko-question/files/533469/mvip_1e.png.for.issue.32.zip) (replaces one file, `mvip_1e.png`, in `umineko\bmp\background\mainbuilding`)

I have also uploaded the generated csv file way back when I was doing the backgrounds, which you can see here: https://github.com/07th-mod/umineko-question/blob/master/widescreen/background_mapping/Background%20Tracker.csv

**Comment by drojf** [comment]
I think this is fixed now.
