### ISSUE TITLE
Default automode timing is broken

### ISSUE THREAD

**Issue by Knurek-NC** [07th-mod/umineko-question#34]
Using the default value of automode_time -50 leads to excessive delays - up to 5 seconds between each line. Gets rather annoying.

As stated on ponscripter github, it `[may not support negative values](https://github.com/sekaiproject/ponscripter-fork/issues/22)`, I got around it by changing the script to automode_time 750 which works okay most of the time (the value may be increased to 1000 or above for slower readers, as there are some pages that end on an unvoiced text)

But there are some issues with voiced samples being skipped over while in automode - can be easily checked during the festival scene in EP2, where Jessica's girlfriends shout over each other about Kanon - you're getting only the first 750 ms (I guess, didn't time it) of each sample, which isn't really enough to play it to completion.

**Comment by marakeusz** [comment]
I feel you pain. We partially discussed it in #22 .

The delays are not set to match actual voice's lengths, so there will be the moments they will be too short. Most of the times they are good, though.

I "fixed" it for myself and make sure the additional wait signs (@) are placed between each voices. (did not committed it yet). I know it is hardly a fix for someone who uses the automode.

You can read in #22 that putting proper delays is not impossible without a little (or more) effort.

**Comment by drojf** [comment]
@Knurek-NC If you're going to try it, I just realized because of https://github.com/07th-mod/umineko-question/issues/29 (due to incorrect voice lengths reported by FFMPEG) the voice lengths I extracted previously may not be correct. So I have removed the link to the times in https://github.com/07th-mod/umineko-question/issues/22#issuecomment-250881816 , if you actually want the voice lengths just let me know.
