### ISSUE TITLE
Episode 2 Chapel Background

### ISSUE THREAD

**Issue by Magoron** [07th-mod/umineko-question#45]
I want to start off by thanking everyone who has contributed to this mod. Thanks to you, Umineko is worthy of being on Steam.

That said, in Episode 2, I noticed the background of the outside/front entrance of the chapel is inconsistent. So far, I've seen it happen once the kids/Rosa/Nanjo go back outside after the first and (showing of) the second twilights. It seems to randomly switch from cha_o2a (the correct background) to cha_o2b, which is very similar but has one of lion's heads twisted to the side. It might not be noticeable to many on their first playthrough, but it was a glaringly obvious change when you know what it means. 

I just wanted to report this issue. As I have absolutely no knowledge of coding and the like, it would be much appreciated if someone could fix this. Thanks!

**Comment by ReitoKanzaki** [comment]
I'll take a look at it when I get home.

**Comment by drojf** [comment]
Thanks for reporting the issue

Looks like the old umitweak version just used the same image (`cha_o2a`) twice. And the original umineko didn't even have a lion in the background for either of the images. 

It appears that the rotated lion originated from Forteissimo's image pack. 

I forgot whether there is any reason for the lion to be rotated at this time in the game or if it makes any difference or not... @ReitoKanzaki I'll leave it to you to decide since you played the game recently. If it's actually meant to change then we have to edit the script, but I think that's not the case and we can just use the same image in both cases (esp since the original umineko didn't even have a lion in the background images...).

**Comment by ReitoKanzaki** [comment]
Thank you for bringing this issue to my attention.

Correct. This issue came from Forteissimo's image pack. Regardless of whether the lion was in there or not, `cha_o2b` is originally meant to be a shot of a path leading to the chapel. I do not know if there is any significance to the rotated lion head or not. I will go ahead and correct this. All `cha_o2b` references will point to `cha_o2a` for now.

**Comment by jwgrlrrajn** [comment]
There is a significance to it, but I can guarantee with the red truth (if these comments actually allowed colored text, anyway) that **there is no reason the lion's head should be turned at this point in the story**. By all rights, that head shouldn't be turning until Chiru.

**Comment by ReitoKanzaki** [comment]
That's what I figured. Fortissimo's image pack used ALL of the PS3 BGs as a base. All I did was change the alias to point to the correct image. 

I think we should do this for all duplicate BGs as it's a quick way to consolidate those images. It would ultimately save disk space.

**Comment by drojf** [comment]
The mapping I used of which ps3 image was used for each PC image is here, from that you can extract the duplicates: https://github.com/07th-mod/umineko-question/blob/master/widescreen/background_mapping/Background%20Tracker.csv (if there is a duplicate in the second column then the image has been reused)

Since fixing the duplicates doesn't affect user experience, probably leave it till later since you're already busy doing the CGs whatnot.

**Comment by drojf** [comment]
This issue has been fixed by making `cha_o2a.png` and `cha_o2b.png` the same image (the non-rotated version). I don't know when it was fixed, or by whom, but it's fixed now so I'll close this thread.
