### ISSUE TITLE
Credits for EP3 don't trigger

### ISSUE THREAD

**Issue by Yugikun** [07th-mod/umineko-question#49]
Hi again. I was able to play to the end of episode 3, but right before the credits at the end (with the cast and when they died), the game just cuts to a blank screen with Dread of the Grave playing, where nothing happens. I can just skip to the next episode, but I would like to be able to complete the episode for myself (so that I can get the steam achievement, among other things). Is there a way that I can fix this issue?

**Comment by DoctorDiablo** [comment]
That's really weird, it's working for me.  Can you double-check that this image is installed in your Umineko folder? Umineko\en\bmp\background\efe\end_3a.png

Someone else had a problem the other day because another image was missing, so maybe it's the same situation.  If the image is actually missing, try reinstalling the patch and see if it adds it in properly.

**Comment by ItaloKnox** [comment]
Just did a check on the patch and the file is definitely there. This should be an installation issue.

**Comment by Yugikun** [comment]
...That's weird. I checked and the file is there, named end_3a. https://gyazo.com/bbe627c4486aca9ab0d2c89345a2982d here's a picture. It turned out that there were extra credits stuff that didn't install from the mod, but even when I add them to the file nothing changes, which is weird.

Also, changing the file name to add a .png at the end also doesn't work.

**Comment by drojf** [comment]
Hey yugikun, 

- as a test, modify one of the key images and see if anything actually changes. Keep in mind not all the images are used, but OP0101 should be used, so open it in paint and draw a smiley face on it or something. I say this because the game could be drawing the images from some other file path. 

- can you post the complete file path to the directory you screencaptured? (just screencapture including the file path bar - your capture is missing the file path bar). Also, the location where the .exe is located would be nice. 

- did you patch from stock-> 1.1? I ask this because I know the game prefers files on disk to files in the main archive file. So there is a difference between someone who went from version 1.0->1.1 to someone who went from stock->1.1 if you replaced the main archive file

**Comment by Yugikun** [comment]
- I put a face on "text001" and that was able to change an image within the actual game. https://gyazo.com/8c78caad3472346bc225cf3cf539f80b
- Here you go: https://gyazo.com/6bb95532c90c25d62ed6bc334f84f007
- I went from 1.0 to 1.1

**Comment by drojf** [comment]
This is a long shot but you did remember to update the script file as well yea?

    mov $witchh4,"bmp\background\efe\end_3a.jpg

was [changed](https://github.com/07th-mod/umineko-question/commit/2ebbe2d13c9ef26cd16764cfcab0323fec491cd9#diff-2294917ab8caed809b97634c8158249eL183777) to

    mov $witchh4,"bmp\background\efe\end_3a.png

So if you didn't update the script, the image wouldn't display. I say it was a long shot because heaps of stuff should be broken as well if this were the case. But yea, check the script actually contains the .png version and not the .jpg version. You could also try modifying that line to point to "text001.png" and seeing if that displays.

Also, ignore the fact that there is no "en" filename prefix - the game will search in the "en" directory if English mode is enabled (I think).

**Comment by Yugikun** [comment]
I did update the script. Just in case though, I opted to redownload it, but the problem's still there.

**Comment by drojf** [comment]
Checked this just now and the ep3 ending does play (albeit too slowly?). Also noticed it overshoots the scroll by about 10 pixels so there's a little black bar when reaching the end of the scroll. I'll just assume this was an installation issue and close this issue.
