### ISSUE TITLE
Voice can't match with Japanese subtitles

### ISSUE THREAD

**Issue by Kaiteinomen** [07th-mod/umineko-question#52]
Hi all, I don't know whether if you only deal with English subtitles or not, but just want to say voice can't match with Japanese subtitles. If you decided not to deal with Japanese subtitles, you may skip this issue. Thanks!

**Comment by drojf** [comment]
I guess none of the projects really dealt with the Japanese subtitles, since the assumption is you could have bought the PS3 game and played it legally that way. Sorry, we probably won't ever support it. 

HOWEVER, I would check out the 'umineko project' version (google it), I believe they may support it.
