### ISSUE TITLE
Voice lines shifted forward by one line if playing in Japanese

### ISSUE THREAD

**Issue by jumpkain** [07th-mod/umineko-question#54]
I'm playing on the Steam release, and all voice files seem to be off by one line when playing with the language set to Japanese. This means that instead of a given voice line playing as soon as its corresponding text begins to appear on screen, the voice line will not play until you click enough to advance to the next voice line trigger. This means that oftentimes you'll hear a voice line for text that isn't even onscreen anymore. The voices work just fine when playing in English - they play at the appropriate times.

I've tested this up until Battler's first line of dialogue in Episode 1, meaning the issue persists there as well as through the part beforehand with Kinzo, Nanjo, and Genji.

**Comment by DoctorDiablo** [comment]
The English and Japanese text are on separate lines in the script, and all the voice clips were added to the English lines:

> langjp「え？！@　おお、@詳しいな！@/
> langen:dwave 0, but_1e469:^"Huh?!^@:dwave 0, but_1e470:^  Wow, ^@:dwave 0, but_1e471:^you sure know a lot about it!^@/

I'm actually a little surprised that the voice clips play at all when the language is set to Japanese.  I assumed that all the langen lines would just be ignored.  Fixing this would be really difficult though, I can't think of a way to fix this without modifying every voiced line in the script.  You're going to see this problem throughout all 4 episodes, so you might be better off playing in English if the audio is bothering you.

**Comment by junshell** [comment]
I'm writing a crude script to move all of the voice prompts from the English lines to the Japanese lines.
When I'm done testing it I will upload it.

**Comment by kumitom** [comment]
I've made a 0.utf for japanese text for own use. But actually there's too many difference between japanese text and english text, so I have to destroy all english text script.

**Comment by Grix** [comment]
@junshell @kumitom 
If you could post your edited 0.utf files if they work with Japanese text, I would appreciate it

**Comment by zengzh72** [comment]
Is there any way to make two 0.utf files for two languages？

**Comment by ItaloKnox** [comment]
Not as far as I know. The game will only load one script at a time.

**Comment by kumitom** [comment]
@Grix
Here is my 0.utf. Sorry for didn't reply faster.
BTW, the english language won't work correctly I think, and not sure whether the japanese language has any bugs. Lots of place is changed by hand, because the number of sentences is different between two languages.

[0.zip](https://github.com/07th-mod/umineko-question/files/1588151/0.zip)

**Comment by drojf** [comment]
@kumitom , can I have a look at the script you used to make the japanese version? I was interested in applying it to the Answer arcs as well.

I can try doing it myself but thought I might as well use whatt you've done already.

**Comment by kumitom** [comment]
@drojf , I did this job by VBA (paste all lines to EXCEL, and paste it back to utf file after done), and checked all errors by hand.
When I checked it, I just open the sound file and listen, then set it to the right place, because I failed to find a common way to solve all problems.
So, I don't think this can help, but anyway I'll post it if you need it.
[umineko vba code.txt](https://github.com/07th-mod/umineko-question/files/1901152/umineko.vba.code.txt)

**Comment by drojf** [comment]
Thanks for your comment, at least I know how difficult it will be to do this task given your description of how you did it, and the code you've written.

**Comment by drojf** [comment]
Japanese is supported for the question and answer arcs so I'll close this now (NOTE: full patch only, not voice only or ADV mode).
