### ISSUE TITLE
Text offset in English (Mac)

### ISSUE THREAD

**Issue by runningcrane** [07th-mod/umineko-question#55]
I know #30 mentioned the background being offset. However, in full screen I'm seeing the text & textbox shade shunted left instead. 
![screen shot 2017-02-11 at 4 26 40 pm](https://cloud.githubusercontent.com/assets/9300981/22858014/b75ccb3e-f077-11e6-84a4-7f9b72dc71ff.png)

**Comment by drojf** [comment]
my initial thought is you didnt patch the script file at all. did you
replace the 0.utf file with the provided patched one (must have same name)?

**Comment by runningcrane** [comment]
Yes, I believe so. I replaced 0.utf with the patched version and replaced the Mac umineko4. They've got the same names as the old ones, and the old ones are backed up under a different name.

**Comment by drojf** [comment]
so there are two things I could think of:

1. The game is not executing the 0.utf you think it's executing
2. Your 0.utf was replaced (maybe by steam or something)

To test number 1, move 0.utf to your desktop and then attempt to run the game. The game shouldn't run at all - if it does run, then maybe it's executing some other script file.

To test number 2, open the 0.utf file which you think the game is executing, then search for `setwindow`

```
;if %UMINEKOEND < 50 mov %UMINEKOEND,50
setwindow 137,16,25,20,23,23,0,2,20,1,1,#999999,0,0,853,479
lsph TextCC1SpNum,":bl/3,160,2;bmp\cursor0.png",0,0
```

The last two numbers of the setwindow command should be the same as above (the last two numbers should be "853, 479". If they are not then your 0.utf file is the wrong one - you should redownload and replace the 0.utf file.

**Comment by runningcrane** [comment]
Sorry for the late response. Thanks for all the help; I got it working. The 0.utf I was previously running did indeed get replaced. I don't know if this is what happened, but this is my best guess:
- I never gave executable permission to 0.utf
- Steam replaced the -x-less 0.utf with the original 0.utf when it couldn't find it
So I redownloaded it, gave it permission, and now it's fine.

**Comment by quaternionkahler** [comment]
May I ask how  you give the 0.utf file permission? Probably a dumb question but I'm hopeless at this stuff.

**Comment by ItaloKnox** [comment]
Since he's running OSX, the way to give permission is to use [chmod](http://www.thegeekstuff.com/2010/06/chmod-command-examples).

**Comment by quaternionkahler** [comment]
I'm quite confused. What exactly am I typing into the terminal?

**Comment by ItaloKnox** [comment]
I'm not sure how much is exactly needed in a personal computer (I mostly work with servers), but this one should be enough: ``chmod 755 0.utf``

Try running it inside the game folder. You can also try to run ``chmod -R 755 gamefolder/`` if it doesn't work. Just make sure to change ``gamefolder`` to its right destination.

**Comment by quaternionkahler** [comment]
I successfully gave executable permission, however the problem is still there.

-When I remove the 0.utf file entirely, the game doesn't play. 

-When I use my old 0.utf file, it shows the ps3 sprites, but the backgrounds and voices aren't there. 

-When I use the new 0.utf file, all of the ps3 stuff shows up, but the text (even in the title screen) is shifted to the right.

Plus, whichever 0.utf file I use, the game has black bars at either side of the screen (i.e. it's not fullscreen).

**Comment by ItaloKnox** [comment]
Did you try [this](https://github.com/07th-mod/umineko-question/raw/master/InDevelopment/ManualUpdates/0.utf) file? The proper steps to check if you are running the right stuff is right here in this thread, so if it doesn't work for you, I'll reopen the issue and we can work to fix it.

**Comment by drojf** [comment]
Hmm...Sounds similar to this:
https://github.com/07th-mod/umineko-question/issues/56

Although I already added this to the main install instructions so you may
have done it already...

**Comment by quaternionkahler** [comment]
I tried the steps on this thread but they don't work for me.

1. When I remove the 0.utf file entirely, the game doesn't run.
2. When I checked to see if it was replaced, it wasn't.

**Comment by drojf** [comment]
Just to be sure, have you tried the steps in the post marked "SOLUTION": https://github.com/07th-mod/umineko-question/issues/56#issuecomment-284396896

Specifically, unzipping the Umineko1to4_patched.app.zip next to the normal Umineko1to4.app file and running that instead of the normal one.

I already added that to the installation instructions for MacOS but you might have missed it.

**Comment by drojf** [comment]
oh wait wtf you're the same person, sorry I didn't notice

**Comment by drojf** [comment]
now I have more questions, so when you applied the fix in the  previous thread, did it not fix the problem? if so, you said "The patched file worked. Thank you :)", so what exactly did the patch I gave you fix?

I suspect that you're running the old umineko1to4.app and not the new one I gave you in the other thread, hence it's not 16:9 and the text is shifted to the right.

**Comment by quaternionkahler** [comment]
Before the umineko4 file wouldn't let my game play no matter what until you sent the patched file. It started playing after that but then I came across the shifted text (due to 0.utf).

After giving permission to both 0.utf and the patched file, it finally is working. I'm quite confused however, because I distinctly remember giving permission to the patched file before.

Thank you again, for helping despite my ineptitude.
