### ISSUE TITLE
Replacing umineko4 makes it unplayable?

### ISSUE THREAD

**Issue by quaternionkahler** [07th-mod/umineko-question#56]
Replacing umineko4 with the umineko4_FOR_MAC_USERS makes a message show that says 'Umineko1to4 can't be opened'. I'm totally useless at this stuff, so apologies if there's a super obvious answer.

**Comment by drojf** [comment]
I think you only forgot to rename the `umineko4_FOR_MAC_USERS`  as `umineko4` but I'll post the full instructions below anyway:

1.  Download the [`umineko4_FOR_MAC_USERS`](https://github.com/07th-mod/umineko-question/releases/download/v2.0/umineko4_FOR_MAC_USERS) file
2.  Rename it as umineko4
3.  Overwrite the exiting file located at `Umineko\Umineko1to4.app\Contents\MacOS\umineko4`

**Comment by quaternionkahler** [comment]
When I do that I get this message; 'The application Umineko1to4 can't be opened.'

**Comment by ItaloKnox** [comment]
Can you run the game fine without the patch? Also, is your OSX up to date?

Worst case scenario they did update the executable and we have to repatch it.

**Comment by drojf** [comment]
also, are tou running the steam version or the mangagamer version? if you
could submit your original umineko4 file that might help too

**Comment by quaternionkahler** [comment]
The game runs without the patch, even just replacing the 0.utf file works (although it shifts all the text to one side, with black bars at both sides of screen). I think my OSX is up to date; it's Sierra.

I am using the Steam version. Also, if I verify integrity of game cache, it brings back my old umineko4 file so that it will run again. Here's the old umineko4 file:

[umineko4 old.zip](https://github.com/07th-mod/umineko-question/files/821071/umineko4.old.zip)

**Comment by drojf** [comment]
I'm at a bit of a loss here (the file you gave me is exactly the same as mine, so everything seems OK), however it may be a security issue or a file permissions issue.

As for file permissions, you can [try and give executable rights like so](https://www.reddit.com/r/osx/comments/30ovah/question_error_message_the_application_cant_be/):

    chmod +x Umineko1to4.app/Contents/MacOS/*

And if it's a security issue (presumably because the program was detected as changed since the first time it was run):

> "OS X: About Gatekeeper" - https://support.apple.com/en-us/HT202491
> 
> "Error: The application 'Steam' can't be opened" - https://steamcommunity.com/discussions/forum/2/458604254461190576/

Finally you can try this. I made up a fake new .app bundle so that maybe MacOS treats it as a 'new install' or 'first time run' and bypasses the security check (I just renamed the names in the config file). Just place side-by-side to the existing `Umineko1to4.app` folder. It is already patched - you just need to run it.

[Umineko1to4_patched.app.zip](https://github.com/07th-mod/umineko-question/files/821256/Umineko1to4_patched.app.zip)

**Comment by quaternionkahler** [comment]
The patched file worked. Thank you :)
