### ISSUE TITLE
Witch voices do not play

### ISSUE THREAD

**Issue by Zmflavius** [07th-mod/umineko-question#61]
Hi all,

I'm playing the Steam version of this game. Overall, the patch seems to work (backgrounds and sprites are all ps3 version, and most voices play), but for some reason, voices for Beatrice, Bernkastel, Lambdadelta, and Stakes of Purgatory do not play (and presumably other witches, but I've only finished the first two episodes so far). So, for example, in Tea Party 1, all voices play as expected except for Beatrice's; likewise, while skipping to another character's line ordinarily cuts off the preceding character's line, if the next line's is Beatrice's, the preceding character finishes their line normally.

I also replayed scenes from eps 1 and 2, tea parties 1 and 2, and ???? 1 and 2, and in no case did I find a missing non-witch character line but also did not hear any witch character voice play.

For clarity, I installed the patch after finishing 2 episodes, not after originally installing the game, and I installed the 2.5 patch directly over the original game, with no intermediate patches.

**Comment by ItaloKnox** [comment]
Hello, I manage this project but unfortunately I'm not well versed in the current developments. This patch is pretty much built over many workarounds and unfortunately I can't keep up with everything because I'm actively working on Higurashi instead. Anyway, just to make sure that I will probably ask a few dumb questions.

So, first things first: have you tried to see if the issues happens as well if you do not load a save and start a new game from any chapters? Maybe try moving away your save for a moment and test it.

I also very recently (yesterday, if I recall correctly) pushed a new update to the voice patch that fixes a few broken voices. Not sure if it is your problem, but you can get the files you need [here](https://diamondz.tk/files/umineko_steam_ps3mod_voicefix.zip). This file was uploaded by one of our developers, so you won't need to download the whole voice patch again.

**Comment by drojf** [comment]
I wonder if it could be as simple as some voice files are missing? 

Check the folder:

```
stralias bea_2e1,"voice\27\20700001.ogg" 
stralias bea_2e2,"voice\27\20700002.ogg" 
stralias bea_2e3,"voice\27\20700003.ogg" 
stralias bea_2e4,"voice\27\20700004.ogg" 
stralias bea_2e5,"voice\27\20700005.ogg" 
stralias bea_2e6,"voice\27\20700006.ogg" 
...
```

which is Beatrice's episode 2 folder, and see if you can play the files in there, or if the files are there at all.

**Comment by Zmflavius** [comment]
I checked the voice files, and it turns out all the voice files after 19 were missing, so I assume that's the source of the issue.  Whoops!

Thanks very much for the quick response!
