### ISSUE TITLE
Umineko Chiru Patch Thread

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-question#68]
Looks like we have a date now (assuming there are no delays): [November 17th](https://www.reddit.com/r/visualnovels/comments/77jtsl/umineko_answer_arc_coming_out_november_17_can/)

For any newcomers, here are the old threads:

- [Patch Thread 1](https://github.com/07th-mod/umineko-question/issues/1)
- [CGs Thread](https://github.com/07th-mod/umineko-question/issues/38)
- [Forteissimo's patches thread](https://github.com/07th-mod/umineko-question/issues/58)

For now I figure we can do the following (if people feel like it), even though the game's not out yet:

- [ ] ~~Extract the voice lines from the old chiru patched script ( @DoctorDiablo ?)~~ Do when game comes out as one step.
- [ ] Fix the .ogg voice files (assuming some of them were broken like last time)
- [ ] Prepare the background images (I was going to do the basic version of this using a script, like I did last time)
- [ ] Prepare the sprites?
- [ ] Prepare to use the installer ( ItaloKnox )
- [ ] Work on misc things:
    - [ ] Prevent the steam .exe being overwritten

I decided to start this thread as I wanted to start work on the backgrounds, but I should check in with everyone else before I get started.

I figure for now I can extract the mapping between the ps3 background images and the old chiru's background images as .csv file (automatically, not manually), so later we can quickly export the backgrounds at whatever resolution we choose.  Possibly I could do the same with the sprites automatically, to save some manual labor.

Also this is a pretty stupid question but how do you Higurashi guys communicate? Do you use an external forum or something? Discord? I think setting something up for chiru would be worthwhile

**Comment by ItaloKnox** [comment]
> Work on misc things like an installer (use the Higurashi installer) or organize who's doing what.

Yeah, that's the main point I wanted to discuss. The Umineko patch is ages behind the Higurashi patch but that's only because the engine makes it difficult and the size of the game also doesn't help. I'll be in charge of the installer and the new installation procedures. I already have a pretty good idea of what I have to do so we can completely ditch the git approach we've been using to deliver the binaries, so overall that is going to make the patch a lot easier to update this time. If things go well, I'll also push the same setup to our previous patch.

Now, as you should already expect, I can't help much with this side of the project other than making sure it is properly released and functional. I really love Umineko so I want to give more attention to it and try to have the same quality control we have in Higurashi, but that's all I can do for now.

In case you need the graphics assets, [I have this archived tool](https://github.com/ItaloKnox/ps3umi) that should do the job. I also have a personal copy of the game in my OneDrive, let me know if you want me to share it. I should also be able to share my copy of the old patched game so we can use the base script and already extracted voice lines as well. Just ask if you need it.

> Also this is a pretty stupid question but how do you Higurashi guys communicate? Do you use an external forum or something? Discord? I think setting something up for chiru would be worthwhile

We've been only using Github since the start. We have a separate repo for all our automation stuff and programming, [the issues section](https://github.com/07th-mod/higurashi-patch-compiler/issues/) should give you an idea of how we do this. As you probably already know, there are no rules or anything against doing the development/discussion outside of here, so if you want to create something just go ahead. I also believe I gave you proper permissions to create your own repos. As long as we can maintain the number of repos in control and on topic, you can also create a new repo for development (in case we have tools or anything that shouldn't be in production).

I think I covered everything, but if there's anything else I can help just tell me.

**Comment by ItaloKnox** [comment]
Double posting because I want you to get the notification (in case you read it first in the email like me).

I'm all in for a Discord channel. Perhaps a channel for the entire group should be a good idea, also a nice way to assist the newbies. Let me page @enumag to hear his thoughts, he's pretty much my right arm in everything here. If he agrees with it and wants to take part, I'll be joining as well.

**Comment by enumag** [comment]
I don't really care to be honest. I have no problem with using GH as we did until now, I never used Discord and even though I use Slack (which is pretty much the same thing as Discord afaik) it doesn't strike me as something we must have. I can set it up and be there if that's what you wish though.

**Comment by drojf** [comment]
My thought process was that it might be handy for asking small questions without cluttering up the main github patch thread...but it's nice to have a record of what's been asked/not asked on github, and there aren't that many of us working on it at the same time...yea I think I'd agree with you to leave it for now.

**Comment by ItaloKnox** [comment]
I still think it's a good idea but let's talk about it again after we get busy. I use Discord all the time and it's really useful for discussion and announcements. Depending on how it goes we might find a good reason to use it.

**Comment by DoctorDiablo** [comment]
I'll check my files when I get home from work, but I'm pretty sure I have the script and voice files from the old Umi chiru patch.  So I should be able to just run everything through the voice inserter once MG releases the new script.

When I ran it the first time, it was able to add about 95% of the voices automatically and it identified around 1000 lines that needed manual correction.  It'll take a couple days to fix those.

Seems like we are a lot better prepared this time, so we should be able to get it done pretty quickly.

**Comment by drojf** [comment]
Hmmm... it looks like when UmiTweak did chiru, they used the same file paths and file names as in the PS3 version

Original / WitchHunt version / Steam Version
```
stralias garden_Se1a,"BMP\background\garden\garden_Se1a.bmp"  ;庭　１枚目
stralias garden_Se1aP,"BMP\background\garden\garden_Se1aP.bmp"  ;庭　１枚目
stralias garden_Se1b,"BMP\background\garden\garden_Se1b.bmp"  ;庭　２枚目
stralias garden_Se1c,"BMP\background\garden\garden_Se1c.bmp"  ;庭　３枚目
```

Umitweak Chiru v1.0 

```
stralias garden_se1ap ":c;bg\garden_se1ap.png"
stralias garden_se1b ":c;bg\garden_se1b.png"
stralias garden_se2b ":c;bg\garden_se2b.png"
stralias garden_se2bp ":c;bg\garden_se2bp.png"
stralias garden_se4a ":c;bg\garden_se4a.png"
```
    
I'll try to do something similar to what has been done with the voices and try to match the straliases (probably based on the immediately previous and next line after each bg call). Then all that has to happen is the raw ps3 images can be resized without resorting them into folders or anything. In addition if UmiTweak has made any changes for whatever reason, we should get them in our script too (or at least I can see what changes they've made)

**Comment by DoctorDiablo** [comment]
Looks like the Umitweak version of Chiru handles the voices slightly differently than the original arcs.  It's not creating the stralias entries for the voices anymore and is just dropping direct paths to the images.

> dwave 0, "voice\27\50700001.ogg":`"You idiot!!`@dwave 0, "voice\27\50700002.ogg":`  Isn't it obvious?!!`@/

I'll do some testing, but I think my code can still handle that because it was just grabbing everything between the comma and colon and inserting that text in the new script.  Hopefully the quotes don't confuse it.

Here's the script file I'm working from, if anyone wants to give it a look.: [chiru_fullvoice.txt](https://github.com/07th-mod/umineko-question/files/1404324/chiru_fullvoice.txt)

**Comment by drojf** [comment]
Some more changes - it looks like they've sometimes put in some of the ps3 sprite variations instead of sticking to one ps3 sprite to replace each sprite in the original game. If we want to preserve everything, we'd probably have to merge the sprite lines from UmiTweak into the main script as it's no longer a one-to-one mapping of old sprite->new sprite. 

The backgrounds do seem one-to-one though.

```
-bg cha_R2b,24
-ld c,KIN_FukigenA1,24                                <- witch hunt version
+bg cha_r2b,24
+ld c,":a;sprites\kin\1\kin_a12_fukigen1.png",24      <- umitweak version
```

eg in the above, even if the witch hunt sprite is the same, sometimes the umitweak sprite will change. I've even seen new sprite change lines included when there weren't any before. 

I've attached a html format diff of the entire script between the witch hunt version and the umitweak version if anyone's interested.
[differences.zip](https://github.com/07th-mod/umineko-question/files/1404640/differences.zip)

**Comment by drojf** [comment]
er this comment just points to the new project, since I didn't get an email form github about it, i thought other people might not as well. Use this thread instead: https://github.com/07th-mod/umineko-answer/issues/1
