### ISSUE TITLE
Can't See the Characters Information Screen

### ISSUE THREAD

**Issue by RevenantMemories** [07th-mod/umineko-question#69]
Um hello, I'd just like to report about not seeing the character information stuff when I installed the patch. So I was wondering if this was due to the new patch or if it was a mistake on my part. I'll attach a picture showing it.
![capture](https://user-images.githubusercontent.com/19716529/32094407-38bbf09e-bb32-11e7-9fac-afebc460f680.PNG)

Edit 1: BTW it's worth mentioning probably that when I clicked jap. it doesn't have any issues with that.

**Comment by ItaloKnox** [comment]
Hi, I'm tagging @Forteissimo here because he is the one who did all the recent changes to the patch. There's a chance he might know what is going on.

**Comment by Forteissimo** [comment]
The only instances where the character bio screen's buggy is on CGs and around four or so certain scenes where a special background is used. Are you using an old save file from before installing the newest patch? Old saves aren't compatible with new versions of the script. In which part of the game exactly is this happening? The character bios have been practically untouched since the original game.

If possible, check that all the images in '...Umineko\en\bmp\r_click\text\cha' are present in the game files.

**Comment by drojf** [comment]
This issue was found again in https://github.com/07th-mod/umineko-question/issues/79 and fixed properly

>Just a question - I noticed that the only way I could get the 'default' steam character text images not to appear was to delete the arc.nsa file in the game directory (which contains the default steam files). Did you delete/rename your arc.nsa file? That's my only explanation as to why this issue wasn't found for so long - most people who have the arc.nsa file will see the default steam images instead of the ones we made for the game.

Basically, one of the folders was not in the right place. The game would load the assets from the arc.nsa file since it couldn't find them. But if you also delete the arc.nsa (please don't do this), then the game can't find them at all, and would just load nothing.

This was solved by moving the folder in the installer script, but in the future the .zip could be updated. But yea, you need to delete the arc.nsa for the problem to be visible.
