### ISSUE TITLE
Missing graphics folder

### ISSUE THREAD

**Issue by RuseHT** [07th-mod/umineko-question#79]
The folder "cha" seems to be missing in the english version, so all the character info are blank on the menu
![image](https://user-images.githubusercontent.com/36344881/36074077-36348c34-0f3b-11e8-99fc-4c42c3d84fff.png)

![image](https://user-images.githubusercontent.com/36344881/36074070-fc285502-0f3a-11e8-836f-e8c9ee419e42.png)

Though it works when i switch to the japanese version.

**Comment by drojf** [comment]
How did you install the game? manual or using the installer?

hmm, is your zip (er .7z) file OK? We've had some issue with corrupted downloads from github - this can cause some images to go missing. You can check the file is OK by either just unzipping it with 7zip or checking the output log, or use the "test zip file option": 

![image](https://user-images.githubusercontent.com/1249449/36080177-440bd844-0fe0-11e8-8efd-bc50f30e34c9.png)

The automated installer automatically verifies the install files to prevent this issue from happening. It's smart enough to detect bad parts of the zip file and re-download just those parts. I can instruct you how to do this if necessary.

**Comment by RuseHT** [comment]
I tried reinstalling using the installer, but the "cha" folder was still missing, even though i did not get any errors. I also tested the zip file with 7-zip, and the file was ok.

**Comment by RuseHT** [comment]
I managed to find all the files under en/bmp/background and the character info seems to appear now. Should i delete the background folder, since it only had files for "efe" and "r_click"?

**Comment by drojf** [comment]
damn...I thought you were talking about the Answer Arcs so I was very confused...we'll try and get that fixed soon. Can't believe this was broken for so long.

I extracted the original assets of the steam game to just to double check the files should be located in ```Umineko\en\bmp\r_click\text\cha```

![image](https://user-images.githubusercontent.com/1249449/36141179-ed40fc92-10f7-11e8-807a-06e41f7cec03.png)

I'll check the other game files are OK and then try to get the zip file updated.

Thanks for providing a detailed report/basically fixing the problem for us 👍  If you have any small questions while playing you can ask on our discord: https://discord.gg/acSbBtD but I would prefer if you have a formal issue to still raise it on github.

**Comment by drojf** [comment]
I always leave the issues open until I actually fix them so I don't forget :)

**Comment by drojf** [comment]
Just a question - I noticed that the only way I could get the 'default' steam character text images not to appear was to delete the `arc.nsa` file in the game directory (which contains the default steam files). Did you delete/rename your arc.nsa file? That's my only explanation as to why this issue wasn't found for so long - most people who have the arc.nsa file will see the default steam images instead of the ones we made for the game.

**Comment by RuseHT** [comment]
I deleted them since i thought they weren't needed, as the files were extracted. So yeah, maybe that's why nobody noticed the issue yet.

**Comment by drojf** [comment]
I...think your game will work correctly, but yea... ideally you want to have it there. If there are any missing images (or anything else) which we forgot to replace, instead of seeing the old image you will just get....nothing. No error message by the game engine either, so you won't even know its missing.

**Comment by drojf** [comment]
Fixed by https://github.com/07th-mod/resources/commit/cdf98c2bb581c7e382907d63a2f5a63a92d5f284 and also adding extra zip file to the wiki.
