### ISSUE TITLE
Delayed text,while audio is playing

### ISSUE THREAD

**Issue by newby24** [07th-mod/umineko-question#86]
I had encountered a small bug, which consists of audio being played 2 or 3s before the text corresponding to that audio, shows up.

it is the line:
W-w-what? Y-Y-you're joking, right?

Line numbers
50305 -50307

script](https://user-images.githubusercontent.com/36610110/36457612-3acef2b2-16ab-11e8-92ab-303fb64f4772.jpg)
I am attaching  screenshot of the scene as well
![script](https://user-images.githubusercontent.com/36610110/36457672-885920ac-16ab-11e8-8e11-cd68b2559a6f.jpg)

**Comment by drojf** [comment]
I think this is the same issue as: https://github.com/07th-mod/umineko-answer/issues/11...we must have forgotten to update the question arcs. Since you know how to edit the script, try changing the `!s0` to `!s1` on those lines and see if it fixes the problem (I haven't tested it yet).

I guess later i'll run my replacer script which should fix this.

**Comment by newby24** [comment]
That fixes it.
Thank you.

**Comment by drojf** [comment]
cool, don't go fixiing it manually, I'll apply the patch to ep1-4 soon

**Comment by drojf** [comment]
Ok i've applied the fix. I think you can get the changes by doing `git rebase master` but maybe talk to me on discord to sort things out.
