### ISSUE TITLE
Kumasawa's portrait not being properly in the scene

### ISSUE THREAD

**Issue by newby24** [07th-mod/umineko-question#90]
As title suggests, during episode 1, there is supposed to be a scene with Kumasawa visible, however, she is almost not visible at all.

**Correct behaviour:**
![correct](https://user-images.githubusercontent.com/36610110/36975558-bb386874-207a-11e8-9d59-2f90673e6d91.jpg)

**Behaviour in the current Steam/Managagamer DRM free release:**
![bug](https://user-images.githubusercontent.com/36610110/36975581-d06b70b0-207a-11e8-9273-4cb07f334ecd.jpg)

**Comment by drojf** [comment]
Just an update on this issue - this occurs many more times in the script. The function which sets the characters to different positions (lsp_var, lsp_var_center etc. ) is used 307 times in the script, which is small enough to manually review (with a script which shows only the times the function is used).

This particular line was added here (although many of the lsp_ functions were added elsewhere): https://github.com/07th-mod/umineko-question/commit/5c63974c2808958eb0e0fb52a5bef7aeb4562d53 by @ReitoKanzaki - If you're still around, just wondering if you remember how you did the conversion? It looks like you did it automatically but it might be manual.

```
langen^From the shadows in the hallway, an old woman wearing an apron watched over them.^@^  It was Kumasawa...^\
 
-lsp_var 1,$KUM_MajimeA1,410,0
+lsp_var 1,$KUM_MajimeA1,547,0  ;convert to widescreen
 ;lsp 800,$KUM_MajimeA1,434,0
 
 print 24
```

**Comment by ReitoKanzaki** [comment]
I was doing those manually. I don't remember this being broken when I made the edits. Were the images altered recently?

**Comment by drojf** [comment]
I'm not sure - right now all the character sprites are the same size as the game resolution (1707x960 I think). If formerly they were just normal size, and it was changed to 1707x960, then yea, that would break it. Do you remember roughly what sizing the sprites used (either the size of the sprite, or the size of the game resolution?)

**Comment by drojf** [comment]
So what I ended up doing to fix this issue was to parse all the lsp_var and lsp_var_trans functions using a script. Then, I make the script generate images which show a 'preview' image of what the game would look like when that command is executed. 

I then looked through the 100 or so images, looking for ones where the sprite was off-screen (there were only about 10 images, just Kumasawa and Beatrice). I then made the script offset those images so that they were on screen (just eyeballed it until the image preview looked correct), and used my sampler script to play through just those bits to verify they actually appear on the screen.

I've added a little information on this lsp_var and related functions here:
https://github.com/07th-mod/umineko-answer/wiki/Script-Reference
